index:
    path: /
    controller: App\Controller\SecurityController::login

home:
    path: /home
    controller: App\Controller\HomeController::home

search:
    path: /search
    controller: App\Controller\SearchController::search

statistics:
    path: /statistics
    controller: App\Controller\StatisticsController::statistics

user:
    path: /user
    controller: App\Controller\UserController::user